---
- hosts: all
  remote_user: root
  sudo: true
  vars_files:
    - 'vars/main.yml'
    - 'defaults/main.yml'
  tasks:
    - include: 'tasks/main.yml'
  handlers:
    - include: 'handlers/main.yml'
