---

- name: Add PPA repository (Ubuntu)
  apt_repository:
    repo: ppa:ondrej/php
    update_cache: true
  when: ansible_distribution == "Ubuntu"

- include: 1-install-Debian.yml
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_version >= 8

- name: Install the php packages (APT)
  apt: >
    name={{ item }}
    state={% if php_fpm_apt_latest is defined and php_fpm_apt_latest == 'yes' %}latest{% else %}present{% endif %}
    update_cache=yes
    cache_valid_time={{ apt_cache_valid_time }}
  with_items: "{{ php_fpm_apt_packages }}"
  environment: "{{ env }}"
  when: ansible_os_family == "Debian"
  notify:
     - restart php-fpm
  tags: [packages,php,fpm]